language: python
cache: pip
sudo: false
dist: trusty

python:
  - "3.4"
  - "3.5"
  - "3.6"

before_install:
  - git fetch --unshallow || true

install:
  - pip install -U pip setuptools
  - pip install --pre pybuilder
  - pyb -X install_dependencies

script:
  - pyb -X

deploy:
  provider: pypi
  user: esc
  distributions: sdist
  skip_cleanup: true
  password:
    secure: "WFp4OBatAedo7THk7LpKFAAXuaryHDtSrZyEt2i2HLzFHAc8N2gz8HJ4C+9k33i16B4sKEBtvWbgvowZwpY1X7Ri+mvz5AfPshF8lTGJV2oyDOtk4CSdsNUWu6i67rYwjWnZ3r+N3xHkCr7Z3xVS+zw5mLw/7hXgHG+sc0iQv8nAhrlE1XB4P9eBfNP6Mr8ogZhCzGTozAVS7m7fZ+Aa9FLeu4DFdnkOftkf1HhcjtAu44reO/69aavgZog+xiH3Ah571rxC1JomTduAXogvWSgDb2fYaWNTgenrqob6lDKA7zz0DEU/1V28bnDuTxjEJ3Qq+G3cbixb166mvx2PE2/7oqc73jHXDn/ckqMfgvzT4sOH+uYm+JTv8WRb4KAe49U/O3zmx98odeODqLLAMQFogX7m2n7+NZfADEWknZ7GGLnokjahEW4CR/FJgRQYUpQUAtXbobpybTh5Lhnh8oiEyKEEaSnSmpereG9hUHD465LHKQ1Xp0Pi2URjXooQSIWkiCveHNiI/ztL9HCHjwBRTzkHBAKnR2OA2zF0ra4Rdfz8b4vBZcCDPUU2YrOq8aVOkw9g9wdOr+LReH7rwvMlj/N1rkTlIGqDpyGgFTI35i91HmPqytUba06zw6t8y4+BKO3KYw7CaqFM5tQQ28jW7xuw/nQHWqJtvyKFrXc="
  on:
    repo: TwentyBN/twentybn-dl
    python: '3.6'
    branch: master
