language: python
cache: pip
sudo: false
dist: trusty

python:
  - "3.4"
  - "3.5"
  - "3.6"

before_install:
  - git fetch --unshallow || true

install:
  - pip install -U pip setuptools
  - pip install --pre pybuilder
  - pyb -X install_dependencies

script:
  - pyb -X

deploy:
  provider: pypi
  user: esc
  distributions: sdist
  skip_cleanup: true
  password:
    secure: "bkjvsbkjkjbdxbkAyGfs5UbaY07BNRUFaaTadS/wu2ZasOtGjxrtr+9woDP7q23QC+iyTPViNhuNqHlub35/syu5NPJDjS/5XR6uBX6Z85qglk+sW0XtztEBO615VG0QUa0QG6jAkjxZpsUjywIUvbpXx1ioHK946gYZfBhNvX/rD/8Fjt34vLBIqfmuhYSJQuVj6OLEuYCXUK6sa2+u1qNPF2zyw13RdP++DaB+ZEWkZLSkT3yMpPvnd1jA3qInVjnDXmchRtsZ3oxMY1fxkDzb3jiGZzNLWw5TYMjENB7Izc3tlkKxqIzZQ0cFHAAuaoVJqxBylzJ2nytGmh0K7fms9n1qVgUGCMtgcYNi8DPT7weQluZ5E/bSnS6+bjFDSKiN2M1UvCpVbuJQiIMi0ZUEXHxOjR4hVIPtBmzzna0qoFUDCLVPz18U/GDK+5Mq225FS/cjC47YgLxWSxnUGnFv4xeTAK+1tt9voZVHDOSDjpB2mtN3oaDVOYDCCbnXusSzl/9rt9kSf0IWoNwwDu8jr36w8JUh7FksOpubDwGxgpAWx1+Ejqud5GWrmsUkAUXeHKtqFOhddc1t0yEMmSF6RPSluOviDwen2jKhmM1tuqpZ/YvpH0hcYQzy9VPc3fSY6zKQzrwtFj399fqnkgcfoKIfldmkeAcKH9G92N6uw5MQ7z+bqYc1U="
  on:
    repo: TwentyBN/twentybn-dl
    python: '3.6'
    branch: master
