language: python
cache: pip
sudo: false
dist: trusty

python:
  - "3.4"
  - "3.5"
  - "3.6"

before_install:
  - git fetch --unshallow || true

install:
  - pip install -U pip setuptools
  - pip install --pre pybuilder
  - pyb -X install_dependencies

script:
  - pyb -X

deploy:
  provider: pypi
  user: esc
  distributions: sdist
  skip_cleanup: true
  password:
    secure: "nkGWfS3V/raE7pWERBmIvup3SoezCnG1NXqjgYp89aVXsXJis5THcRPJ+1W024SVtvA8/TpIBMDTr7dPzU1c4rH31BAYGjytjU106Mrrld//cKYwV5XI16r4f3GW7my+eMozP8fwWZiOESAxst9gqJ4hKdSxjW+Azx3Qd9noi/KzCLZZxxvSEiNMEzoj73pVZrXtVuLHyK9R4aRBWmeV8998wn7YMqlRsDmtCF21t8zy2JJUP4ScyZ7xrYUl4nLPqEcxqkysxwWWvj5WTFPvWN0l1uxxlt2qT2Cqofv+w+qr1SSUEbZyLGTmyjb7mwWKBRa3NPrwmJ4O9vDKFqocdcVCWxW8VDbFHTSchqAb35jFLFXulzfdkGb7AzfYsuQg2zidCKlQwWqTmv15qhRwjKRUdd//fG5o/Px91I9wPm4jFVPXho7WMcY+pYB7D9qJGjk2BfXZFbYWaaw0hZt8sjvRnF7E3cQiYQbfjc6tmQ8sttvvSnptk6W4krEGVjaQNpnyO/WC9LtbvouY3yi3bH63vE+fr9zV/1MvuB6eorYPZblSUEgL0bC5JF7u5qVDHYwtkvK892wHbn6bpDUYPcZ412PMAZM4GDW5jrmGJCl+EqtZ2pAbpFLT5Iw5/nkDMQA4oykTUhJSjMixDXiePfcb4bh5EJnOwXWkbV4qWqM="
  on:
    repo: TwentyBN/twentybn-dl
    python: '3.6'
    branch: master
