language: python
cache: pip
sudo: false
dist: trusty

python:
  - "3.4"
  - "3.5"
  - "3.6"

before_install:
  - git fetch --unshallow || true

install:
  - pip install -U pip setuptools
  - pip install --pre pybuilder
  - pyb -X install_dependencies

script:
  - pyb -X

deploy:
  provider: pypi
  server: https://upload.pypi.org/legacy/
  user: esc
  distributions: sdist
  skip_cleanup: true
  password:
    secure: "UvqcXiJVR73h0hU410rON0NuvRulFP5TIlLis1FeMSY/wUrxg2Vg9xJDwnsv2a1qm0ZPdwBmvMa40WiazB28CcCQfYgIrYga5BNICUEHKUOHfyZWFApvZcEdRDz2acql+cte2CgSooFWPoTd3R5RSmbzfL69dDEPu6BngQXAfH+2WaroOl61yimduZOqfKBjbE4n+3CLCosgPUB2U/oE80kE15HIWO6OBlQDVako5PrvwaTrq7QKNsTpUsJSr1vuzcXVsBi5OaU0linVmx1PJcYFx2hU1j/nPu2euLfF8A+B6uIiP0u/26trwfInViou4vnn2/5h8i0QF0WKRHF9/y/F+GWxxBVWZF6BqOXAvRD4neDFpbGiK4DZeT9JxV8M7bDJAS57OEGeSI2gf62vNnsa9ILVLtQlH2piUEy2a6afustWd0ptG6wFT79FHlFc5iO0HW81gjbITo5JEwBWsiWg+H3ZwCdmO0/ztxJcwGo6K2tTIfXdr83556ozm8+/6pVS61rhx/DpQB6XYg9aRUUbScX96+281QyWScQdJb+So5VkkaK4V7Kssa/J5GX5l2eMmHI/63lYMEGxl14yKLDPaYM1aczqZuU0ji/1Y9LXiiKkJwW6e1mDj0SdfIcRC1CAjCqgSJOFs7yhVzSqJhmj22Aiylc5ecCknTfcKaI="
  on:
    repo: TwentyBN/twentybn-dl
    python: '3.6'
    branch: master
