language: python
cache: pip

python:
  - "3.4"
  - "3.5"
  - "3.6"

before_install:
  - git fetch --unshallow || true

install:
  - pip install -U pip setuptools
  - pip install --pre pybuilder
  - pyb -X install_dependencies

script:
  - pyb -X

deploy:
  provider: pypi
  user: esc
  distributions: sdist
  skip_cleanup: true
  password:
    secure: "n/7H6hP7xayDZOQtmIv8ef/L7SbPN6hTKMrvuUBsQp7rLELTPx4Hs4+JijcTT/O4URajD3WLPnPz2gertc8hBJh2+5brJaPMIdZfpqO2YhaAADfR7GQz4MitIB7UhqLEd+QFcwgQerih5qTRXDsN0jX0UhQ2HuaTDr9w034Zoz0pkheR/P8o4Gjo9y5d2eunugNBqmqFL3PnrS6GpIMDQdn+mTw98jgt3EfVLlYGL/ZSWj8w+dE7qYGzxvkZauCu7e9sqaCE2umjwWbMRc2AYAohcyLqH4Q1FG1+UsE8HDWSnJlCvijPvhyzK895p4fO8JxLhqAvAUJxAC/MeCFmCu+kuJmoFDR2uNV1OsKDdiOIFw3AcOE21pFjw1EoiJY/CpvN0cm3JFjgZPaemakKk72RDc6eNGuM35bbSnFhh8O9yfkz/Y+pzuFEq9PmQ4W6O/DCRCAUNEvyc/U3pP1YvL1aL8RPzvjEXU0xWrOX0F/BiHpTMa+BaFYBE5NLzDx4JopX2SXCrUf3nfZH0weTknH6DHtz21+G2xfOdmDPSKxVEJADyFDrVdIZHm07NvXg4BPfvD0PG/Ne9Vx+Xs3xHnw4rCrpQQu9zcGQR+pUqiz940+riBDROGxap8iO7YX7iQLsTjkFd+JJ0DKc98P5NPRap0sqUKwnw4bTvIzrctc="
  on:
    repo: TwentyBN/twentybn-dl
    python: '3.6'
    branch: master
after_deploy:
  - cat $HOME/.pypirc
