language: python
cache: pip

python:
  - "3.4"
  - "3.5"
  - "3.6"

before_install:
  - git fetch --unshallow || true

install:
  - pip install -U pip setuptools
  - pip install --pre pybuilder
  - pyb -X install_dependencies

script:
  - pyb -X

deploy:
  provider: pypi
  user: esc
  distributions: sdist
  skip_cleanup: true
  password:
    secure: "GOPAh1y13jrZZBEi2OTb/iZMiUlcW5wHy9m/RmE3uLP+T2KrF2zrFWsg3J8mXQ+HqxqJx54j8/KGJWoTU2qrSHxTQZ/Z67yaoCszcvvX+kabd8XJsoDQh4SKVg4LT7UnS1oos1h3TC4avza23A5aByo/U+BZDMc3KdoKepNUAo8EN2d+jjJHBe9Bx2A2Kj5cQjsOS3p782AdvSnmZm9+rSBwPtkHFkXTUVMjyhTC9+dThuzlt9FWihuhJuEk6grMHtA6qzP91OS02E8DKNcQhwa84xaqOi2z3BPjy08abX+m0rrjr7ajyFvrv5jxS0HjaauPDVeuc7PsQmncNn9iE+8ihBXs0ra412qqvcFc2NVciSpxeZGR+5hIW8U3tTtmrKtJV82A8NEc4qJE7wPmO+z83SGM6+fSEhBRHWbSTtu1DgX1+NABcqIQcWQ/zKp6X6EhThqCE/2sur2anKrQBN9aUfoWP7amAA+j+CP0oM3L1HogKvZ5J3MhuIgDDGCFIH6mwmsGfG/YjfJCrhmcbu61naT2F9CmqZmfhwjCk5KYLK8MtFfkRTv1P7jjddMUK8HkRjltRgItKMb5kZCOABw8AuBgXFhwtkFsst+zj8YF3IkCl5fl7aFK0A8RDAVZICkTLdPuJ4SEBPybMLJ3fWbCRJt/jA+6HKQH9Pu4P1I="
  on:
    repo: TwentyBN/twentybn-dl
    python: '3.6'
    branch: master
after_deploy:
  - cat $HOME/.pypirc
